import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {
    MatButtonModule,
    MatSelectModule,
    MatToolbarModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatProgressBarModule,
    MatCardModule,
    MatDividerModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatLineModule,
    MatListModule,
    MatChipsModule,
    MatBadgeModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatDialogModule,
    MatGridListModule,
    MatSortModule,
    MatTableModule,
    MatPaginatorModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatTabsModule,
    MatExpansionModule,
} from '@angular/material';

@NgModule({
    imports: [
        CommonModule,
        MatButtonModule,
        MatSelectModule,
        MatToolbarModule,
        MatFormFieldModule,
        MatIconModule,
        MatInputModule,
        MatProgressBarModule,
        MatCardModule,
        MatDividerModule,
        MatSnackBarModule,
        MatCheckboxModule,
        MatLineModule,
        MatListModule,
        MatChipsModule,
        MatBadgeModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatDialogModule,
        MatGridListModule,
        MatPaginatorModule,
        MatSortModule,
        MatTableModule,
        MatSlideToggleModule,
        MatSidenavModule,
        MatTabsModule,
        MatExpansionModule,
        MatCheckboxModule
    ],
    exports: [
        MatButtonModule,
        MatSelectModule,
        MatToolbarModule,
        MatFormFieldModule,
        MatIconModule,
        MatInputModule,
        MatProgressBarModule,
        MatCardModule,
        MatDividerModule,
        MatSnackBarModule,
        MatCheckboxModule,
        MatListModule,
        MatChipsModule,
        MatBadgeModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatDialogModule,
        MatGridListModule,
        MatPaginatorModule,
        MatSortModule,
        MatTableModule,
        MatSlideToggleModule,
        MatSidenavModule,
        MatTabsModule,
        MatExpansionModule,
        MatCheckboxModule
    ],
    declarations: []
})
export class MaterialModule {}
